<?php

namespace TaskPlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findAllByUserId($id)
    {
        $data = $this->getEntityManager()->createQuery('Select tasks From TaskPlannerBundle:Task tasks Where tasks.user = '.$id.' Order By tasks.deadLine ASC')
                ->getResult();
        return $data;
    }
    public function findAllByTaskId($id)
    {
        $data = $this->getEntityManager()->createQuery('Select tasks From TaskPlannerBundle:Task tasks Where tasks.user = '.$id.' Order By tasks.id DESC')
                ->getResult();
        return $data;
    }
}
